### PR TITLE
Initialize connection with DB and Create models

### PR DESCRIPTION
**Pull request by doonpy**
- Database connection is localhost.
- Models: User, History and Character (use mongoose).
- This commit include testing files in test folder (user mocha framework and chai library).
- ' is change to " ("JavaScript (ES6) code snippets" extension).

### CODE REVIEW

**Comment by huynhlehieunam** [comment]
username, email of User.model should be unique.

**Comment by PhanThiMai** [comment]
*** user :
avatar ???

**Comment by doonpy** [comment]
Update model user rồi nha :3

**Comment by doonpy** [comment]
Đã cập nhật thêm model "Invitation"

**Pull request merged**
